### ISSUE TITLE
Problem with request dependency

### ISSUE THREAD

**Issue by manico** [apollographql/apollo-engine-js#120]
I use in my project apollo-engine `^0.8.9` and it is not working as `request` dependency is giving error `uuid is not a function`.

I guess the problem is because I also use uuid package (latest) in my project.
Is this a problem that apollo engine can fix or request package?
Either way, apollo-engine does not work in this scenario.

Error:

```
TypeError: uuid is not a function
    at new Multipart (/code/project/node_modules/request/lib/multipart.js:10:19)
    at new Request (/code/project/node_modules/request/request.js:125:21)
    at request (/code/project/node_modules/request/index.js:53:10)
    at Promise (/code/project/node_modules/apollo-engine/lib/middleware.js:66:30)
```

**Comment by manico** [comment]
I found that the problem is with `https://github.com/standard-things/esm` as we use it.
