### ISSUE TITLE
engine sometimes throws unhandled exceptions communicating with subprocess

### ISSUE THREAD

**Issue by glasser** [apollographql/apollo-engine-js#131]
We've observed stack traces like:

```
Error: This socket has been ended by the other party
 at Socket.writeAfterFIN [as write] (net.js:351:12)
 at StreamJsonObjects.logStream.output.on (/app/bundle/programs/server/npm/node_modules/apollo-engine/lib/index.js:169:37)
 at emitOne (events.js:116:13)
 at StreamJsonObjects.emit (events.js:211:7)
 at addChunk (_stream_readable.js:263:12)
...
```

I've also seen
```
Error: read ECONNRESET 
 at _errnoException (util.js:1022:11)
```
and
```
Error: write EPIPE
 at _errnoException (util.js:1022:11)
 at WriteWrap.afterWrite (net.js:867:14)
```
in the same process. This may not be Engine-related but it seems plausible.

Basically this seems like non-ideal error handling when Engine exits which causes us to lose Engine's own error output.  I think we can simplify the interactions between the two processes so that it's easier to correctly set up error handling.

**Comment by glasser** [comment]
All the relevant code was rewritten in v0.9.0.  We believe that this came from communicating with engineproxy over stdio, but apollo-engine v0.9.0 minimizes how much of that is done:

- it no longer writes config over stdin, preferring to use env vars or files
- it only reads from stdout and stderr if you ask it to write to your custom stream
- it does read from fd 3, but it sets an error handler on it.
