### ISSUE TITLE
Getting goroutine console logging on each file save/server restart

### ISSUE THREAD

**Issue by sbrichardson** [apollographql/apollo-engine-js#141]
I'm using nodemon with apollo server express and apollo engine, I started getting the below log out put on each file save (nodemon restarts the server).

I also noticed that the paths look like a user's local MacOS file system @glasser which seemed odd also.

How can I stop this from logging, without stopping my normal console.logs during development?

I tried changing the Engine log level to Error and disabling tracing. 

```bash
goroutine 21 [running]:
runtime/pprof.writeGoroutineStacks(0x19b33c0, 0xc42000c020, 0xd0, 0xd0)
        /Users/glasser/Projects/Meteor/monorepo/deps/go/go1.10.darwin-amd64/src/runtime/pprof/pprof.go:650 +0xa7
runtime/pprof.writeGoroutine(0x19b33c0, 0xc42000c020, 0x2, 0x30, 0xc42041a698)
        /Users/glasser/Projects/Meteor/monorepo/deps/go/go1.10.darwin-amd64/src/runtime/pprof/pprof.go:639 +0x44
runtime/pprof.(*Profile).WriteTo(0x1e2ce20, 0x19b33c0, 0xc42000c020, 0x2, 0x0, 0x0)
        /Users/glasser/Projects/Meteor/monorepo/deps/go/go1.10.darwin-amd64/src/runtime/pprof/pprof.go:310 +0x3e4
mdg/diagnostics/sigusr2trace.DumpStacksOnSIGUSR2.func1(0xc420182960)
        /Users/glasser/Projects/Meteor/monorepo/go/src/mdg/diagnostics/sigusr2trace/sigusr2trace.go:20 +0x7c
created by mdg/diagnostics/sigusr2trace.DumpStacksOnSIGUSR2
        /Users/glasser/Projects/Meteor/monorepo/go/src/mdg/diagnostics/sigusr2trace/sigusr2trace.go:17 +0xab

goroutine 1 [select (no cases)]:
main.main()
        /Users/glasser/Projects/Meteor/monorepo/go/src/mdg/engine/engineproxy/main.go:213 +0x39a

goroutine 5 [syscall]:
os/signal.signal_recv(0x19b6ea0)
        /Users/glasser/Projects/Meteor/monorepo/deps/go/go1.10.darwin-amd64/src/runtime/sigqueue.go:139 +0xa7
os/signal.loop()
        /Users/glasser/Projects/Meteor/monorepo/deps/go/go1.10.darwin-amd64/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
        /Users/glasser/Projects/Meteor/monorepo/deps/go/go1.10.darwin-amd64/src/os/signal/signal_unix.go:28 +0x41

goroutine 16 [select, locked to thread]:
runtime.gopark(0x1916bc0, 0x0, 0x18a336c, 0x6, 0x18, 0x1)
        /Users/glasser/Projects/Meteor/monorepo/deps/go/go1.10.darwin-amd64/src/runtime/proc.go:291 +0x11a
runtime.selectgo(0xc420463750, 0xc4202dcba0)
        /Users/glasser/Projects/Meteor/monorepo/deps/go/go1.10.darwin-amd64/src/runtime/select.go:392 +0xe50
runtime.ensureSigM.func1()
        /Users/glasser/Projects/Meteor/monorepo/deps/go/go1.10.darwin-amd64/src/runtime/signal_unix.go:549 +0x1c6
runtime.goexit()
        /Users/glasser/Projects/Meteor/monorepo/deps/go/go1.10.darwin-amd64/src/runtime/asm_amd64.s:2361 +0x1

goroutine 22 [select]:
io.(*pipe).Read(0xc4200e2460, 0xc420398000, 0x1000, 0x1000, 0x1743200, 0x1, 0xc420398000)
        /Users/glasser/Projects/Meteor/monorepo/deps/go/go1.10.darwin-amd64/src/io/pipe.go:50 +0x115
io.(*PipeReader).Read(0xc42019c010, 0xc420398000, 0x1000, 0x1000, 0x1000, 0x1000, 0x0)
        /Users/glasser/Projects/Meteor/monorepo/deps/go/go1.10.darwin-amd64/src/io/pipe.go:127 +0x4c
bufio.(*Scanner).Scan(0xc4200a4f38, 0x0)
        /Users/glasser/Projects/Meteor/monorepo/deps/go/go1.10.darwin-amd64/src/bufio/scan.go:208 +0xbf
mdg/vendor/github.com/sirupsen/logrus.(*Entry).writerScanner(0xc4200e22d0, 0xc42019c010, 0xc420364040)
        /Users/glasser/Projects/Meteor/monorepo/go/src/mdg/vendor/github.com/sirupsen/logrus/writer.go:51 +0xab
created by mdg/vendor/github.com/sirupsen/logrus.(*Entry).WriterLevel
        /Users/glasser/Projects/Meteor/monorepo/go/src/mdg/vendor/github.com/sirupsen/logrus/writer.go:43 +0x1b9

goroutine 23 [select]:
mdg/engine/engineproxy/tracing.(*statsState).startProcessing.func1(0xc4200f6150)
        /Users/glasser/Projects/Meteor/monorepo/go/src/mdg/engine/engineproxy/tracing/stats.go:113 +0x142
created by mdg/engine/engineproxy/tracing.(*statsState).startProcessing
        /Users/glasser/Projects/Meteor/monorepo/go/src/mdg/engine/engineproxy/tracing/stats.go:110 +0x3f

goroutine 24 [select]:
mdg/engine/engineproxy/tracing.(*tracesState).startProcessing.func1(0xc4202fa0a0)
        /Users/glasser/Projects/Meteor/monorepo/go/src/mdg/engine/engineproxy/tracing/traces.go:133 +0x139
created by mdg/engine/engineproxy/tracing.(*tracesState).startProcessing
        /Users/glasser/Projects/Meteor/monorepo/go/src/mdg/engine/engineproxy/tracing/traces.go:130 +0x3f

goroutine 25 [chan receive]:
main.Start.func1(0xc4203284e0, 0xc4200f62a0, 0xc42018a240)
        /Users/glasser/Projects/Meteor/monorepo/go/src/mdg/engine/engineproxy/main.go:85 +0x52
created by main.Start
        /Users/glasser/Projects/Meteor/monorepo/go/src/mdg/engine/engineproxy/main.go:84 +0x474

goroutine 50 [select]:
mdg/engine/engineproxy/tracing.(*Reports).SetConfig.func1(0xc4200e25f0, 0xc4200f61c0, 0x19ba260, 0xc420350040)
        /Users/glasser/Projects/Meteor/monorepo/go/src/mdg/engine/engineproxy/tracing/reports.go:67 +0x121
created by mdg/engine/engineproxy/tracing.(*Reports).SetConfig
        /Users/glasser/Projects/Meteor/monorepo/go/src/mdg/engine/engineproxy/tracing/reports.go:65 +0x167

goroutine 51 [IO wait]:
internal/poll.runtime_pollWait(0x226cfa0, 0x72, 0x0)
        /Users/glasser/Projects/Meteor/monorepo/deps/go/go1.10.darwin-amd64/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4201acf18, 0x72, 0x0, 0x0, 0x0)
        /Users/glasser/Projects/Meteor/monorepo/deps/go/go1.10.darwin-amd64/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc4201acf18, 0xffffffffffffff00, 0x0, 0x0)
        /Users/glasser/Projects/Meteor/monorepo/deps/go/go1.10.darwin-amd64/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc4201acf00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/glasser/Projects/Meteor/monorepo/deps/go/go1.10.darwin-amd64/src/internal/poll/fd_unix.go:372 +0x1a8
net.(*netFD).accept(0xc4201acf00, 0x1916cf0, 0xc4203500c0, 0xc4204a6f28)
        /Users/glasser/Projects/Meteor/monorepo/deps/go/go1.10.darwin-amd64/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc42019c028, 0xc42033e688, 0x1, 0xc42033e690)
        /Users/glasser/Projects/Meteor/monorepo/deps/go/go1.10.darwin-amd64/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).AcceptTCP(0xc42019c028, 0xc4204e5e70, 0x10e54aa, 0x17f9c60)
        /Users/glasser/Projects/Meteor/monorepo/deps/go/go1.10.darwin-amd64/src/net/tcpsock.go:246 +0x49
mdg/engine/engineproxy/enginehttp.(*Listener).Accept(0xc42033e680, 0xc4200300d8, 0x1772640, 0x1e29cc0, 0x1872fe0)
        /Users/glasser/Projects/Meteor/monorepo/go/src/mdg/engine/engineproxy/enginehttp/enginehttp.go:39 +0x61
net/http.(*Server).Serve(0xc4203961f0, 0x19b7320, 0xc42033e680, 0x0, 0x0)
        /Users/glasser/Projects/Meteor/monorepo/deps/go/go1.10.darwin-amd64/src/net/http/server.go:2770 +0x1a5
mdg/engine/engineproxy/frontend.(*httpService).Start.func1(0xc4203400d0, 0xf, 0xc4203961e0, 0xc42033e680)
        /Users/glasser/Projects/Meteor/monorepo/go/src/mdg/engine/engineproxy/frontend/http.go:66 +0xfa
created by mdg/engine/engineproxy/frontend.(*httpService).Start
        /Users/glasser/Projects/Meteor/monorepo/go/src/mdg/engine/engineproxy/frontend/http.go:60 +0x15b

goroutine 26 [chan receive]:
main.Start.func2(0xc4200f62a0, 0xc42018a240)
        /Users/glasser/Projects/Meteor/monorepo/go/src/mdg/engine/engineproxy/main.go:123 +0x66
created by main.Start
        /Users/glasser/Projects/Meteor/monorepo/go/src/mdg/engine/engineproxy/main.go:120 +0x5fc

```

**Comment by glasser** [comment]
As hinted at by the DumpStacksOnSIGUSR2 function name in the stack trace, you're hitting a diagnostic feature of the proxy where it dumps stack traces of all of its threads (goroutines) when it receives the SIGUSR2 signal.

It looks like nodemon also chooses to use the SIGUSR2 signal by default as a "hey, we're going to restart you soon, graceful shutdown please" signal.  And in fact, it looks like it goes out of its way to send it to every process descended from the process it has spawned. That's an unfortunate overlap.

It looks like you can give nodeman the `signal` config parameter and pass, say, `SIGUSR1` to tell it to use USR1 instead for its graceful shutdown signal.  That should be an effective workaround.

If lots of users run into this, we could change the diagnostic signal (say, to USR1) — but there really are a limited number of signals out there, and any of them might conflict with a popular tool. I'm surprised nodemon chose USR2 for this (rather than SIGHUP or even SIGUSR1).

**Comment by jbreuer95** [comment]
@glasser I think you guys should change it to SIGUSR1 because now you need 2 nodemon restarts before the proxy works again. I think most people will be using nodemon. This makes developing really hard with the proxy on.

**Comment by glasser** [comment]
Good call. I've implemented that in the proxy binary and it should get into our next release.

**Comment by jbreuer95** [comment]
Awesome!

**Comment by glasser** [comment]
This will be in 1.0
