### ISSUE TITLE
Galaxy deploy bug with Apollo Engine in Windows

### ISSUE THREAD

**Issue by guippiccoli** [apollographql/apollo-engine-js#185]
So... I was using Apollo Engine on Galaxy and it was fine until I try deploying from Windows.  The deploy goes well in the machine, but output an error in Galaxy Logs after it tries to "Start Application" - The is pasted below.

Everything works fine deploying from linux. I Contacted Galaxy Support and they sent me here with this response: 
> My guess is that this means that Windows loses the executable bit on the engineproxy binary and then it can't launch it.

Error Log from galaxy:
```
w9dp5
2018-05-22 03:39:45-03:00events.js:183
w9dp5
2018-05-22 03:39:45-03:00 throw er; // Unhandled 'error' event
w9dp5
2018-05-22 03:39:45-03:00 ^
w9dp5
2018-05-22 03:39:45-03:00
w9dp5
2018-05-22 03:39:45-03:00Error: spawn EACCES
w9dp5
2018-05-22 03:39:45-03:00 at _errnoException (util.js:1022:11)
w9dp5
2018-05-22 03:39:45-03:00 at ChildProcess.spawn (internal/child_process.js:323:11)
w9dp5
2018-05-22 03:39:45-03:00 at Object.exports.spawn (child_process.js:502:9)
w9dp5
2018-05-22 03:39:45-03:00 at spawnChild (/app/bundle/programs/server/npm/node_modules/apollo-engine/lib/launcher.js:101:41)
w9dp5
2018-05-22 03:39:45-03:00 at ApolloEngineLauncher.start (/app/bundle/programs/server/npm/node_modules/apollo-engine/lib/launcher.js:164:9)
w9dp5
2018-05-22 03:39:45-03:00 at ApolloEngine.<anonymous> (/app/bundle/programs/server/npm/node_modules/apollo-engine/lib/engine.js:257:60)
w9dp5
2018-05-22 03:39:45-03:00 at step (/app/bundle/programs/server/npm/node_modules/apollo-engine/lib/engine.js:50:23)
w9dp5
2018-05-22 03:39:45-03:00 at Object.next (/app/bundle/programs/server/npm/node_modules/apollo-engine/lib/engine.js:31:53)
w9dp5
2018-05-22 03:39:45-03:00 at /app/bundle/programs/server/npm/node_modules/apollo-engine/lib/engine.js:25:71
w9dp5
2018-05-22 03:39:45-03:00 at new Promise (<anonymous>)
w9dp5
2018-05-22 03:39:45-03:00 at __awaiter (/app/bundle/programs/server/npm/node_modules/apollo-engine/lib/engine.js:21:12)
w9dp5
2018-05-22 03:39:45-03:00 at ApolloEngine.startEngine (/app/bundle/programs/server/npm/node_modules/apollo-engine/lib/engine.js:226:16)
w9dp5
2018-05-22 03:39:45-03:00 at Server.<anonymous> (/app/bundle/programs/server/npm/node_modules/apollo-engine/lib/engine.js:126:19)
w9dp5
2018-05-22 03:39:45-03:00 at Object.onceWrapper (events.js:313:30)
w9dp5
2018-05-22 03:39:45-03:00 at emitNone (events.js:106:13)
w9dp5
2018-05-22 03:39:45-03:00 at Server.emit (events.js:208:7)
w9dp5
2018-05-22 03:39:45-03:00 at emitListeningNT (net.js:1394:10)
w9dp5
2018-05-22 03:39:45-03:00 at _combinedTickCallback (internal/process/next_tick.js:135:11)
w9dp5
2018-05-22 03:39:45-03:00 at process._tickDomainCallback (internal/process/next_tick.js:218:9)
````

**Comment by glasser** [comment]
In the short term, I'd recommend trying to deploy from Linux, perhaps with a CI tool like circleci or travis.  In the longer term, we'll be rolling out a pure-Node engine reporting implementation soon which will solve this problem permanently.
